name: Build Pico Firmware

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install ARM Toolchain and CMake
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential cmake ninja-build

      - name: Clone Pico SDK
        run: |
          git clone --recurse-submodules https://github.com/raspberrypi/pico-sdk.git $HOME/pico-sdk

      - name: Configure and Build
        env:
          PICO_SDK_PATH: ${{ runner.temp }}/../pico-sdk
        run: |
          export PICO_SDK_PATH=$HOME/pico-sdk
          cmake -B build -G Ninja
          ninja -C build

      - name: Upload UF2 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pico-emmc-firmware
          path: build/*.uf2
